#pragma once

#include <stdint.h>
#include <vector>

enum OPCODE : uint8_t
{
	ERROR_SYMBOL = 0,
	ASSEMBLY_BEGIN_DECL,
	ASSEMBLY_END_DECL,
	NAMESPACE_POOL_DECL_SIZE,
	CLASS_POOL_DECL_SIZE,
	ATTRIBUTE_POOL_DECL_SIZE,
	METHOD_POOL_DECL_SIZE,
	METHOD_PARAMS_DECL_SIZE,
	DEPENDENCY_POOL_DECL_SIZE,
	METHOD_BODY_BEGIN_DECL,
	METHOD_BODY_END_DECL,
	STRING_DECL,
	MODIFIERS_DECL,
	PUSH_STRING,
	PUSH_INTEGER,
	PUSH_FLOAT,
	PUSH_OBJECT,
	PUSH_NULL,
	PUSH_TRUE,
	PUSH_FALSE,
	POP_TO_RETURN,
	SET_VAR,
	SET_CONST_VAR,
	NEGATION_OP,
	NEGATIVE_OP,
	POSITIVE_OP,
	ALLOC_PUSH = 27, // 26 means EOF ! okay ...
	SUM_OP,
	SUB_OP,
	MULT_OP,
	DIV_OP,
	MOD_OP,
	POWER_OP,
	ASSIGN_OP,
	SET_ALU_INCR,
};

struct Instruction
{
	uint8_t OPCode;
	Instruction(OPCODE code);
};

typedef std::vector<Instruction> InstructionVector;